export const accessLabels = [
  {
    title: "Level 1",
    category: "General",
    id: "levelOneCheck",
    description:
      "Level 1 users have the highest access across the system. They can manage all aspects of the business, including menus, branches, tickets, and user permissions across all locations.",
    permissions: [
      "Create Menus",
      "View All Menus",
      "Freeze/ Unfreeze Menu List",
      "Edit Menus",
      "Create Branches",
      "Update Branches",
      "Delete Branches",
      "Create QR Codes for Rooms",
      "Create QR Codes for Tables",
      "Generate Online Ordering Link",
      "Generate Self Checkout Link",
      "View Open and Closed Tickets",
      "Void Order for Open and Closed Tickets",
      "Request Refund for Order on Closed Tickets",
      "Vacate Table on Closed Tickets",
      "View Business Report",
      "Download Business Report",
      "Add Users",
      "Accept or Decline Incoming Tickets on Waiter App",
      "Change Order Status on Waiter App",
      "Collect Tips on Waiter App",
      "View Earnings from Tips",
      "Add Menus to Till",
      "Add Modifiers to Till",
      "Hold Orders on Till",
      "Work on Open Tickets on Till",
    ],
  },
  {
    title: "Level 2",
    category: "Inventory",
    id: "levelTwoCheck",
    description:
      "Level 2 users manage their specific branch. They can handle menus, tickets, QR codes, and user roles within their branch, but cannot oversee other branches.",
    permissions: [
      "Create Menus",
      "View All Menus",
      "Freeze/ Unfreeze Menu List",
      "Edit Menus",
      "Create Branches",
      "Update Branches",
      "Delete Branches",
      "Create QR Codes for Rooms",
      "Create QR Codes for Tables",
      "Generate Online Ordering Link",
      "Generate Self Checkout Link",
      "View Open and Closed Tickets",
      "Void Order for Open and Closed Tickets",
      "Request Refund for Order on Closed Tickets",
      "Vacate Table on Closed Tickets",
      "View Business Report",
      "Download Business Report",
      "Add Users",
      "Accept or Decline Incoming Tickets on Waiter App",
      "Change Order Status on Waiter App",
      "Collect Tips on Waiter App",
      "View Earnings from Tips",
      "Add Menus to Till",
      "Add Modifiers to Till",
      "Hold Orders on Till",
      "Work on Open Tickets on Till",
    ],
  },
  {
    title: "Level 3",
    category: "Ticket",
    id: "levelThreeCheck",
    description:
      " Level 3 users have limited access, focusing on daily tasks such as handling tickets, tips, and orders. Their permissions are restricted to specific apps like Troo Till and  Troo Waiter .",
    permissions: [
      "Accept or Decline Incoming Tickets on Waiter App",
      "Change Order Status on Waiter App",
      "Collect Tips on Waiter App",
      "View Earnings from Tips",
      "Add Menus to Till",
      "Add Modifiers to Till",
      "Hold Orders on Till",
      "Work on Open Tickets on Till",
    ],
  },
];
